# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U4YxW1vgrFt8hvmuSqd4w-oCyXpH0vGG

# **`*Group 8*`**

Removed duplicates
 ,Used separate test set
 ,Applied noise to training
 ,Didn’t leak data

The high performance is due to the dataset being relatively simple, rather than overfitting. The models generalize well because there are strong patterns separating spam and ham
"""

!pip uninstall -y torchao
!pip install torchao --upgrade

# Data handling
import pandas as pd
import numpy as np
# Text cleaning
import re
import nltk
# Visualization
import seaborn as sns
import matplotlib.pyplot as plt
# ML tools
from collections import Counter
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import (classification_report, confusion_matrix, f1_score,
                             precision_score, recall_score, roc_auc_score,
                             precision_recall_curve, auc)
from sklearn.neural_network import MLPClassifier
# LLM tools
import torch
from transformers import (DistilBertTokenizer, DistilBertForSequenceClassification,
                          TrainingArguments, Trainer)
# LoRA (efficient training)
from peft import get_peft_model, LoraConfig, TaskType

nltk.download('stopwords')
# Stopwords (common useless words like "the", "is")
from nltk.corpus import stopwords
from sklearn.metrics import accuracy_score

from google.colab import files
uploaded = files.upload()
df = pd.read_csv(list(uploaded.keys())[0])
df.head()

print("Shape before dedup:", df.shape)
df = df.drop_duplicates(subset='email')
print("Shape after dedup:", df.shape)

#removig duplicates
stop_words = set(stopwords.words('english'))

#Makes text easier for models to understand
def clean_text(text):
    text = text.lower()                   # make lowercase
    text = re.sub(r'[^a-z\s]', '', text)  # remove symbols
    words = text.split()                   # split into words
    words = [w for w in words if w not in stop_words]
    return " ".join(words)
# Apply cleaning to all emails
df['clean_text'] = df['email'].apply(clean_text)
# ham = 0, spam = 1
df['label'] = df['label'].map({'ham': 0, 'spam': 1})
df = df.sample(frac=1, random_state=42).reset_index(drop=True)

print(df['label'].value_counts())

import random
random.seed(42)

noise_rate = 0.2  # 20% wrong labels
# randomly pick samples to flip
noise_indices = random.sample(range(len(df)), int(len(df) * noise_rate))

df['noisy'] = False
df.loc[noise_indices, 'noisy'] = True

print(f"Marked {len(noise_indices)} samples as noisy")
print(df['label'].value_counts())

sns.countplot(x=df['label'])
plt.title("Spam vs Ham Distribution")
plt.xticks([0, 1], ['Ham', 'Spam'])
plt.show()

ham_words = " ".join(df[df['label'] == 0]['clean_text']).split()
spam_words = " ".join(df[df['label'] == 1]['clean_text']).split()

print("Top 10 HAM words: ", [w for w, _ in Counter(ham_words).most_common(10)])
print("Top 10 SPAM words:", [w for w, _ in Counter(spam_words).most_common(10)])
print()
print(f"Total unique emails after dedup: {len(df)}")

# forces models to generalize harder
# also experimented with a larger test split (70%), which reduced training data and caused performance issues,
#especially for smaller models. However, I selected a more balanced split for final evaluation to ensure stability and fairness.
X_train, X_test, y_train, y_test = train_test_split(
    df['clean_text'], df['label'],
    test_size=0.6,          # 60% test
    stratify=df['label'],
    random_state=42
)

print(f"Train size: {len(X_train)}, Test size: {len(X_test)}")

#Converts words to numerical features
tfidf = TfidfVectorizer(max_features=300)
X_train_tfidf = tfidf.fit_transform(X_train)
X_test_tfidf  = tfidf.transform(X_test)

# Apply noise only to training labels

y_train = y_train.copy()
# find which training samples are noisy
noisy_mask = df.loc[X_train.index, 'noisy']
# flip labels (0 → 1, 1 → 0)
y_train[noisy_mask] = 1 - y_train[noisy_mask]

print(f"Flipped {noisy_mask.sum()} training labels")
print(f"Train label distribution:\n{y_train.value_counts()}")

mlp_base = MLPClassifier(
    hidden_layer_sizes=(64,), # simple model (1 layer)
    max_iter=300,
    random_state=42
)
mlp_base.fit(X_train_tfidf, y_train)
y_pred_base = mlp_base.predict(X_test_tfidf)
y_prob_base = mlp_base.predict_proba(X_test_tfidf)[:, 1]
print("MLP Base trained.")

mlp_enhanced = MLPClassifier(
    hidden_layer_sizes=(128, 64), # deeper model
    max_iter=300,
    alpha=0.0001,               # regularization
    early_stopping=True,        # stop before overfitting
    validation_fraction=0.15,  # hold out 15% of train for early stopping
    n_iter_no_change=20,
    random_state=42
)
mlp_enhanced.fit(X_train_tfidf, y_train)
y_pred_enhanced = mlp_enhanced.predict(X_test_tfidf)
y_prob_enhanced = mlp_enhanced.predict_proba(X_test_tfidf)[:, 1]
print("MLP Enhanced trained.")

#preparing LLM Data
tokenizer = DistilBertTokenizer.from_pretrained('distilbert-base-uncased')

# convert text to tokens
#converting  raw text into a format that a language model (like DistilBERT) can understand and use.

train_encodings = tokenizer(list(X_train), truncation=True, padding=True, max_length=128)
test_encodings  = tokenizer(list(X_test),  truncation=True, padding=True, max_length=128)

class SpamDataset(torch.utils.data.Dataset):
    def __init__(self, encodings, labels):
        self.encodings = encodings
        self.labels = labels.reset_index(drop=True)

    def __getitem__(self, idx):
        item = {key: torch.tensor(val[idx]) for key, val in self.encodings.items()}
        item['labels'] = torch.tensor(self.labels[idx])
        return item

    def __len__(self):
        return len(self.labels)

train_dataset = SpamDataset(train_encodings, y_train)
test_dataset  = SpamDataset(test_encodings,  y_test)
print("Datasets ready.")

#This uses Hugging Face Transformers
"""
FOR each epoch:
    FOR each batch:
        1. Predict
        2. Compare with true label
        3. Calculate loss
        4. Update weights
"""
def train_model(model, name):
    training_args = TrainingArguments(
        output_dir=f'./{name}',
        num_train_epochs=5,
        per_device_train_batch_size=16,
        per_device_eval_batch_size=16,
        save_strategy="no",
        report_to="none"
    )
    trainer = Trainer(
        model=model,
        args=training_args,
        train_dataset=train_dataset,
        eval_dataset=test_dataset,
    )
    trainer.train()
    preds = trainer.predict(test_dataset)
    y_pred = np.argmax(preds.predictions, axis=1)
    y_prob = torch.softmax(torch.tensor(preds.predictions), dim=1)[:, 1].numpy()
    return y_pred, y_prob

#loading a pretrained model from DistilBERT
base_model = DistilBertForSequenceClassification.from_pretrained(
    'distilbert-base-uncased', num_labels=2
)
y_pred_llm, y_prob_llm = train_model(base_model, "base_llm")
print("DistilBERT base trained.")

#training DistilBERT using LoRA (a lightweight fine tuning method)

# only modifying Query (Q) and Value (V) inside DistilBERT
#Lora is small tuning chip
fresh_model_small = DistilBertForSequenceClassification.from_pretrained(
    'distilbert-base-uncased', num_labels=2
)
lora_small = LoraConfig(
    task_type=TaskType.SEQ_CLS,
    r=4,       # small rank
    lora_alpha=16,
    lora_dropout=0.1,
    target_modules=["q_lin", "v_lin"]
)
model_lora_small = get_peft_model(fresh_model_small, lora_small)
model_lora_small.print_trainable_parameters()
y_pred_lora_small, y_prob_lora_small = train_model(model_lora_small, "lora_small")
print("LoRA Small trained.")

"""
LoRA trains DistilBERT by:
-Freezing the original model
-Adding small trainable matrices (A and B)
-Learning only those
-Slightly modifying outputs
"""

#LoRA fine tunes DistilBERT by adding small trainable updates to selected attention layers (q_lin and v_lin) while keeping the original model weights frozen.
#Q (query) → decides what to look at
#V (value) → decides what information to pass
#R  controls how complex the adjustment is

fresh_model_large = DistilBertForSequenceClassification.from_pretrained(
    'distilbert-base-uncased', num_labels=2
)
lora_large = LoraConfig(
    task_type=TaskType.SEQ_CLS,
    r=16,
    lora_alpha=32,
    lora_dropout=0.1,
    target_modules=["q_lin", "v_lin"]
)
model_lora_large = get_peft_model(fresh_model_large, lora_large)
model_lora_large.print_trainable_parameters()
y_pred_lora_large, y_prob_lora_large = train_model(model_lora_large, "lora_large")
print("LoRA Large trained.")

def evaluate(name, y_true, y_pred):
    print(f"\n{'='*40}\n{name}")
    print(classification_report(y_true, y_pred, target_names=['Ham', 'Spam']))
    return {
        "Accuracy":  accuracy_score(y_true, y_pred),
        "F1":        f1_score(y_true, y_pred),
        "Precision": precision_score(y_true, y_pred),
        "Recall":    recall_score(y_true, y_pred),
        "ROC-AUC":   roc_auc_score(y_true, y_pred)
    }

results = {}
results["MLP Base"]     = evaluate("MLP Base",     y_test, y_pred_base)
results["MLP Enhanced"] = evaluate("MLP Enhanced", y_test, y_pred_enhanced)
results["DistilBERT"]   = evaluate("DistilBERT",   y_test, y_pred_llm)
results["LoRA Small"]   = evaluate("LoRA Small",   y_test, y_pred_lora_small)
results["LoRA Large"]   = evaluate("LoRA Large",   y_test, y_pred_lora_large)

results_df = pd.DataFrame(results).T
print(results_df)

fig, axes = plt.subplots(1, 5, figsize=(20, 4))
models = {
    "MLP Base":     y_pred_base,
    "MLP Enhanced": y_pred_enhanced,
    "DistilBERT":   y_pred_llm,
    "LoRA Small":   y_pred_lora_small,
    "LoRA Large":   y_pred_lora_large,
}
for ax, (name, preds) in zip(axes, models.items()):
    cm = confusion_matrix(y_test, preds)
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', ax=ax)
    ax.set_title(name)
    ax.set_xlabel("Predicted")
    ax.set_ylabel("Actual")

plt.tight_layout()
plt.show()

results_df.plot(kind='bar', figsize=(10, 5), ylim=(0, 1.05))
plt.title("Model Comparison")
plt.ylabel("Score")
plt.xticks(rotation=15)
plt.legend(loc='lower right')
plt.tight_layout()
plt.show()

"""# ***Running Across 5 seeds for all models to prove our results***"""

from transformers import set_seed as hf_set_seed

seeds = [42, 7, 123, 2024, 99]

all_scores = {
    "MLP Base": {"f1": [], "acc": []},
    "MLP Enhanced": {"f1": [], "acc": []},
    "DistilBERT": {"f1": [], "acc": []},
    "LoRA Small": {"f1": [], "acc": []},
    "LoRA Large": {"f1": [], "acc": []}
}

for seed in seeds:
    print(f"\n===== Seed {seed} =====")

    # Set all random seeds
    np.random.seed(seed)
    torch.manual_seed(seed)
    hf_set_seed(seed)

    # Split
    X_tr, X_te, y_tr, y_te = train_test_split(
        df['clean_text'], df['label'],
        test_size=0.6, stratify=df['label'], random_state=seed
    )

    # Noise
    y_tr = y_tr.copy()
    y_tr[df.loc[X_tr.index, 'noisy']] = 1 - y_tr[df.loc[X_tr.index, 'noisy']]

    # TF-IDF
    tfidf = TfidfVectorizer(max_features=300)
    X_tr_tfidf = tfidf.fit_transform(X_tr)
    X_te_tfidf  = tfidf.transform(X_te)

    # MLP Base
    base = MLPClassifier(hidden_layer_sizes=(64,), max_iter=1000, random_state=seed)
    base.fit(X_tr_tfidf, y_tr)
    all_scores["MLP Base"]["f1"].append(f1_score(y_te, base.predict(X_te_tfidf)))
    all_scores["MLP Base"]["acc"].append(accuracy_score(y_te, base.predict(X_te_tfidf)))

    # MLP Enhanced
    enh = MLPClassifier(hidden_layer_sizes=(128,64), max_iter=1000, alpha=0.0001,
                        early_stopping=True, random_state=seed)
    enh.fit(X_tr_tfidf, y_tr)
    all_scores["MLP Enhanced"]["f1"].append(f1_score(y_te, enh.predict(X_te_tfidf)))
    all_scores["MLP Enhanced"]["acc"].append(accuracy_score(y_te, enh.predict(X_te_tfidf)))

    # Rebuild datasets for LLMs
    tokenizer = DistilBertTokenizer.from_pretrained('distilbert-base-uncased')
    train_encodings = tokenizer(list(X_tr), truncation=True, padding=True, max_length=128)
    test_encodings  = tokenizer(list(X_te),  truncation=True, padding=True, max_length=128)
    train_dataset = SpamDataset(train_encodings, y_tr)
    test_dataset  = SpamDataset(test_encodings,  y_te)

    # DistilBERT
    base_model = DistilBertForSequenceClassification.from_pretrained('distilbert-base-uncased', num_labels=2)
    y_pred_llm, _ = train_model(base_model, f"base_llm_seed{seed}")
    all_scores["DistilBERT"]["f1"].append(f1_score(y_te, y_pred_llm))
    all_scores["DistilBERT"]["acc"].append(accuracy_score(y_te, y_pred_llm))

    # LoRA Small
    fresh_small = DistilBertForSequenceClassification.from_pretrained('distilbert-base-uncased', num_labels=2)
    model_lora_small = get_peft_model(fresh_small, LoraConfig(
        task_type=TaskType.SEQ_CLS, r=4, lora_alpha=16,
        lora_dropout=0.1, target_modules=["q_lin","v_lin"]))
    y_pred_ls, _ = train_model(model_lora_small, f"lora_small_seed{seed}")
    all_scores["LoRA Small"]["f1"].append(f1_score(y_te, y_pred_ls))
    all_scores["LoRA Small"]["acc"].append(accuracy_score(y_te, y_pred_ls))

    # LoRA Large
    fresh_large = DistilBertForSequenceClassification.from_pretrained('distilbert-base-uncased', num_labels=2)
    model_lora_large = get_peft_model(fresh_large, LoraConfig(
        task_type=TaskType.SEQ_CLS, r=16, lora_alpha=32,
        lora_dropout=0.1, target_modules=["q_lin","v_lin"]))
    y_pred_ll, _ = train_model(model_lora_large, f"lora_large_seed{seed}")
    all_scores["LoRA Large"]["f1"].append(f1_score(y_te, y_pred_ll))
    all_scores["LoRA Large"]["acc"].append(accuracy_score(y_te, y_pred_ll))

    print(f"Seed {seed} complete.")

# ===== FINAL SUMMARY =====
print("\n\n===== FINAL RESULTS ACROSS 5 SEEDS =====")
print(f"\n{'Model':<20} {'Mean F1':>8} {'F1 Std':>8} {'Mean Acc':>10} {'Acc Std':>8}")
print("-" * 60)
for model, scores in all_scores.items():
    print(f"{model:<20} {np.mean(scores['f1']):>8.4f} {np.std(scores['f1']):>8.4f} {np.mean(scores['acc']):>10.4f} {np.std(scores['acc']):>8.4f}")

# ===== VISUALIZATION =====
fig, axes = plt.subplots(1, 2, figsize=(14, 5))
colors = ['blue', 'orange', 'green', 'red', 'purple']

for i, (model, scores) in enumerate(all_scores.items()):
    axes[0].plot(seeds, scores['f1'], marker='o', label=model, color=colors[i])
    axes[1].plot(seeds, scores['acc'], marker='o', label=model, color=colors[i])

axes[0].set_title("F1 Score Across 5 Seeds")
axes[0].set_xlabel("Seed")
axes[0].set_ylabel("F1 Score")
axes[0].set_ylim(0.7, 1.05)
axes[0].legend()

axes[1].set_title("Accuracy Across 5 Seeds")
axes[1].set_xlabel("Seed")
axes[1].set_ylabel("Accuracy")
axes[1].set_ylim(0.7, 1.05)
axes[1].legend()

plt.tight_layout()
plt.show()